wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722793446
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 15
      - 23
      4: 3.9.7
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
seed:
  desc: null
  value: 0
dataset:
  desc: null
  value: kings
test_size:
  desc: null
  value: 0.2
steps:
  desc: null
  value: 10000
lr:
  desc: null
  value: 0.002
weight_decay:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 1024
model_type:
  desc: null
  value: mlp
model_params:
  desc: null
  value: null
num_timesteps:
  desc: null
  value: 1000
gaussian_loss_type:
  desc: null
  value: mse
scheduler:
  desc: null
  value: cosine
gaussian_parametrization:
  desc: null
  value: eps
multinomial_loss_type:
  desc: null
  value: vb_stochastic
parametrization:
  desc: null
  value: x0
embedding_dim:
  desc: null
  value:
  - 128
  - 128
dropout:
  desc: null
  value: 0.0
cuda:
  desc: null
  value: true
